import sqlite3, os
BASE_DIR = os.path.abspath(os.path.dirname(__file__))
DB_DIR = os.path.join(BASE_DIR,'instance')
os.makedirs(DB_DIR, exist_ok=True)
DB_PATH = os.path.join(DB_DIR,'db.sqlite')
conn = sqlite3.connect(DB_PATH)
cur = conn.cursor()
cur.executescript('''PRAGMA foreign_keys=OFF;DROP TABLE IF EXISTS user_progress;DROP TABLE IF EXISTS enroll_requests;DROP TABLE IF EXISTS likes;DROP TABLE IF EXISTS enrollments;DROP TABLE IF EXISTS lessons;DROP TABLE IF EXISTS courses;DROP TABLE IF EXISTS users;PRAGMA foreign_keys=ON;''')
cur.execute('CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT UNIQUE NOT NULL, password TEXT NOT NULL, fullname TEXT, email TEXT, is_admin INTEGER DEFAULT 0)')
cur.execute('CREATE TABLE courses (id INTEGER PRIMARY KEY AUTOINCREMENT, title_ar TEXT, title_en TEXT, short_desc_ar TEXT, short_desc_en TEXT, full_desc_ar TEXT, full_desc_en TEXT, image TEXT)')
cur.execute('CREATE TABLE lessons (id INTEGER PRIMARY KEY AUTOINCREMENT, course_id INTEGER NOT NULL, title_ar TEXT, title_en TEXT, content_ar TEXT, content_en TEXT, position INTEGER DEFAULT 0, video TEXT, FOREIGN KEY(course_id) REFERENCES courses(id) ON DELETE CASCADE)')
cur.execute('CREATE TABLE enrollments (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER, course_id INTEGER, enrolled_at DATETIME DEFAULT CURRENT_TIMESTAMP, UNIQUE(user_id, course_id))')
cur.execute('CREATE TABLE likes (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER, course_id INTEGER)')
cur.execute('CREATE TABLE enroll_requests (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER, course_id INTEGER, requested_at DATETIME DEFAULT CURRENT_TIMESTAMP)')
cur.execute('CREATE TABLE user_progress (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER, lesson_id INTEGER, watched_at DATETIME DEFAULT CURRENT_TIMESTAMP, UNIQUE(user_id, lesson_id))')
cur.execute("INSERT INTO users (username,password,fullname,email,is_admin) VALUES ('admin@gmail.com','adminpass','Admin','admin@example.com',1)")
cur.execute("INSERT INTO users (username,password,fullname,email,is_admin) VALUES ('student1','pass123','Student One','student1@example.com',0)")
cur.execute("INSERT INTO courses (title_ar,title_en,short_desc_ar,short_desc_en,full_desc_ar,full_desc_en,image) VALUES (?,?,?,?,?,?,?)",('تعلم بايثون','Learn Python','مقدمة','Intro','وصف كامل','Full desc','python.jpg'))
course1 = cur.lastrowid
for i,(t_ar,t_en) in enumerate([('مقدمة','Intro'),('المتغيرات','Variables'),('الحلقات','Loops')],start=1):
    cur.execute('INSERT INTO lessons (course_id,title_ar,title_en,content_ar,content_en,position,video) VALUES (?,?,?,?,?,?,?)',(course1,t_ar,t_en,'<p>محتوى</p>','<p>content</p>',i,None))
conn.commit()
conn.close()
print('DB created at', DB_PATH)
